apiVersion: v1
kind: Secret
metadata:
  name: devops-portal-secret
  labels:
    app: devops-portal
type: Opaque
stringData:
  DB_LINK: postgresql://postgres:password@postgres:5432/mydb
  SECRET_KEY: change-me-in-production
  ADMIN_PASSWORD: admin123
  DEVOPS_CAPTAIN_PASSWORD: captain123
