apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: 3-tier-app-eks
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: backend
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'until nslookup devopsdozo-db.cvik8accw2tk.ap-south-1.rds.amazonaws.com; do echo waiting for database; sleep 2; done;']
      containers:
        - name: backend
          image: 879381241087.dkr.ecr.ap-south-1.amazonaws.com/3tier-devopsdozo-backend:341ae01bcb97ce89b38f9fed86dac0b18c9d76a0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: ALLOWED_ORIGINS
              value: "https://devopsdozo.livingdevops.org,http://devopsdozo.livingdevops.org"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DATABASE_URL
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: SECRET_KEY
            - name: FLASK_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: FLASK_DEBUG
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: 3-tier-app-eks
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
