apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devops-quiz-backend
  namespace: 3-tier-app-eks
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - 3-tier-app-eks
  selector:
    matchLabels:
      app: backend
  endpoints:
    - path: /metrics
      interval: 30s
      port: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devops-quiz-frontend
  namespace: 3-tier-app-eks
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - 3-tier-app-eks
  selector:
    matchLabels:
      app: frontend
  endpoints:
    - path: /metrics
      interval: 30s
      port: metrics
