kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraMounts:
  - hostPath: /tmp/kind-storage-worker1
    containerPath: /var/local-path-provisioner
- role: worker
  extraMounts:
  - hostPath: /tmp/kind-storage-worker2
    containerPath: /var/local-path-provisioner
- role: worker
  extraMounts:
  - hostPath: /tmp/kind-storage-worker3
    containerPath: /var/local-path-provisioner
